import type { AiConversationMessage } from "./types";

const internalPromptMarkers = [
  "你是 SmartFocus 的 AI 计划编排助手",
  "请只返回 JSON",
  "当前 skill：",
  "资料摘要（未读取正文",
  "现有任务摘要",
  "RESCHEDULE_CONTEXT",
  "当前 skill：adaptive_reschedule",
  "低 token 原则",
];

const schemaMarkers = [
  '"intent": "learning_planning_preview"',
  '"clarification_questions"',
  '"daily_plan"',
  '"review_rounds"',
  '"adaptive_rules"',
  '"learnkata_links"',
  '"needs_user_confirmation"',
];

export function isInternalPlanningPrompt(content: string): boolean {
  const normalized = content.trim();
  if (!normalized) return false;
  if (internalPromptMarkers.some((marker) => normalized.includes(marker))) return true;
  if (normalized.includes("用户输入：") && normalized.includes("learning_planning_preview")) return true;
  return schemaMarkers.filter((marker) => normalized.includes(marker)).length >= 4
    && (normalized.includes("请只返回 JSON") || normalized.includes("当前 skill："));
}

export function isVisibleConversationMessage(message: Pick<AiConversationMessage, "role" | "content">): boolean {
  return message.role !== "system" && !isInternalPlanningPrompt(message.content);
}

export function filterVisibleConversationMessages(messages: AiConversationMessage[]) {
  return messages.filter(isVisibleConversationMessage);
}

export function firstVisibleUserInput(messages: AiConversationMessage[]) {
  return filterVisibleConversationMessages(messages).find((message) => message.role === "user")?.content.trim() ?? "";
}

export function latestVisibleSummary(messages: AiConversationMessage[]) {
  const visible = filterVisibleConversationMessages(messages);
  return [...visible].reverse().find((message) => message.role === "assistant")?.content.trim()
    ?? [...visible].reverse().find((message) => message.role === "user")?.content.trim()
    ?? "";
}

export function safeConversationTitle(
  title: string,
  messages: AiConversationMessage[],
  goalTitle?: string | null,
) {
  const trimmed = title.trim();
  const looksAutoGenerated = /^未命名/.test(trimmed) || /^新建对话/.test(trimmed);
  if (trimmed && !looksAutoGenerated && !isInternalPlanningPrompt(trimmed)) return trimmed;
  if (goalTitle?.trim()) return goalTitle.trim();
  const firstInput = firstVisibleUserInput(messages);
  return firstInput ? firstInput.slice(0, 20) : "未命名对话";
}

export function safeConversationSummary(messages: AiConversationMessage[]) {
  return latestVisibleSummary(messages) || "该历史仅包含内部上下文，建议删除";
}
